// <auto-generated />
using System;
using CPCREDO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CPCREDO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CpcredoDbContext))]
    [Migration("20260904170951_ServiceClient")]
    partial class ServiceClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CPCREDO.Domain.Accounting.GlAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("account_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_fr");

                    b.Property<string>("NameHt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_ht");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("normal_balance");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_gl_accounts");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_gl_accounts_parent_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_gl_accounts_tenant_id_code");

                    b.ToTable("gl_accounts", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversal");

                    b.Property<string>("JournalNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("journal_no");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_user_id");

                    b.Property<Guid?>("ReversalOfJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_journal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_journal_entries_branch_id");

                    b.HasIndex("PostedByUserId")
                        .HasDatabaseName("ix_journal_entries_posted_by_user_id");

                    b.HasIndex("ReversalOfJournalId")
                        .HasDatabaseName("ix_journal_entries_reversal_of_journal_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_tenant_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("TenantId", "JournalNo")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_tenant_id_journal_no");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("GlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("GlAccountId")
                        .HasDatabaseName("ix_journal_lines_gl_account_id");

                    b.HasIndex("JournalEntryId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_lines_journal_entry_id_line_no");

                    b.ToTable("journal_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_line_one_side", "(debit = 0 AND credit > 0) OR (credit = 0 AND debit > 0)");
                        });
                });

            modelBuilder.Entity("CPCREDO.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_logs_occurred_at_utc");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Audit.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("path");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_idempotency_records_expires_at_utc");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_tenant_id_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description_fr");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name_en");

                    b.Property<string>("DisplayNameFr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name_fr");

                    b.Property<string>("DisplayNameHt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name_ht");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_users_branch_id");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address_line");

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alternate_phone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Cin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cin");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Commune")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("commune");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kyc_status");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("member_no");

                    b.Property<string>("Nif")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("nif");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_members_branch_id");

                    b.HasIndex("TenantId", "Cin")
                        .IsUnique()
                        .HasDatabaseName("ix_members_tenant_id_cin")
                        .HasFilter("cin IS NOT NULL AND cin <> ''");

                    b.HasIndex("TenantId", "MemberNo")
                        .IsUnique()
                        .HasDatabaseName("ix_members_tenant_id_member_no");

                    b.HasIndex("TenantId", "Nif")
                        .IsUnique()
                        .HasDatabaseName("ix_members_tenant_id_nif")
                        .HasFilter("nif IS NOT NULL AND nif <> ''");

                    b.HasIndex("TenantId", "LastName", "FirstName")
                        .HasDatabaseName("ix_members_tenant_id_last_name_first_name");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.MemberTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ticket_no");

                    b.HasKey("Id")
                        .HasName("pk_member_tickets");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_member_tickets_assigned_to_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_member_tickets_created_by_user_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_tickets_member_id");

                    b.HasIndex("TenantId", "TicketNo")
                        .IsUnique()
                        .HasDatabaseName("ix_member_tickets_tenant_id_ticket_no");

                    b.HasIndex("TenantId", "MemberId", "CreatedAtUtc")
                        .HasDatabaseName("ix_member_tickets_tenant_id_member_id_created_at_utc");

                    b.ToTable("member_tickets", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_number_sequences");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_number_sequences_tenant_id_key");

                    b.ToTable("number_sequences", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.ShareAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_no");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<decimal>("ParValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("par_value");

                    b.Property<int>("QualificationShareCount")
                        .HasColumnType("integer")
                        .HasColumnName("qualification_share_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_share_accounts");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_share_accounts_branch_id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_share_accounts_member_id");

                    b.HasIndex("TenantId", "AccountNo")
                        .IsUnique()
                        .HasDatabaseName("ix_share_accounts_tenant_id_account_no");

                    b.ToTable("share_accounts", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_no");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at_utc");

                    b.Property<Guid?>("BlockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_by_user_id");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("blocked_reason");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<decimal>("MinimumBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("minimum_balance");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_savings_accounts");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_savings_accounts_branch_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_savings_accounts_member_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_savings_accounts_product_id");

                    b.HasIndex("TenantId", "AccountNo")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_accounts_tenant_id_account_no");

                    b.HasIndex("TenantId", "MemberId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_accounts_tenant_id_member_id_product_id");

                    b.ToTable("savings_accounts", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entry_type");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid>("SavingsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("savings_account_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TillSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("till_session_id");

                    b.Property<DateTime>("ValueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value_date_utc");

                    b.HasKey("Id")
                        .HasName("pk_savings_ledger_entries");

                    b.HasIndex("SavingsAccountId")
                        .HasDatabaseName("ix_savings_ledger_entries_savings_account_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_ledger_entries_tenant_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("savings_ledger_entries", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsLien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("SavingsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("savings_account_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_savings_liens");

                    b.HasIndex("SavingsAccountId")
                        .HasDatabaseName("ix_savings_liens_savings_account_id");

                    b.ToTable("savings_liens", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashGlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("cash_gl_account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LiabilityGlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("liability_gl_account_id");

                    b.Property<decimal>("MinimumBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("minimum_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_savings_products");

                    b.HasIndex("CashGlAccountId")
                        .HasDatabaseName("ix_savings_products_cash_gl_account_id");

                    b.HasIndex("LiabilityGlAccountId")
                        .HasDatabaseName("ix_savings_products_liability_gl_account_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_products_tenant_id_name");

                    b.ToTable("savings_products", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Teller.TillCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("FaceValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("face_value");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TillSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("till_session_id");

                    b.HasKey("Id")
                        .HasName("pk_till_count_lines");

                    b.HasIndex("TillSessionId")
                        .HasDatabaseName("ix_till_count_lines_till_session_id");

                    b.ToTable("till_count_lines", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Teller.TillSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<decimal?>("CountedCash")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("counted_cash");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("ExpectedCash")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("expected_cash");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<decimal>("OpeningFloat")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("opening_float");

                    b.Property<decimal?>("OverShortAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("over_short_amount");

                    b.Property<Guid?>("OverShortJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("over_short_journal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_till_sessions");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_till_sessions_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_till_sessions_user_id");

                    b.HasIndex("TenantId", "UserId", "BranchId", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_till_sessions_tenant_id_user_id_branch_id_currency_code")
                        .HasFilter("status = 'Open'");

                    b.ToTable("till_sessions", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Tenancy.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHeadquarters")
                        .HasColumnType("boolean")
                        .HasColumnName("is_headquarters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_tenant_id_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DefaultBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_branch_id");

                    b.Property<string>("DisplayTimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_time_zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PrimaryCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("primary_currency");

                    b.Property<string>("SecondaryCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("secondary_currency");

                    b.Property<decimal>("ShareParValue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(500.0000m)
                        .HasColumnName("share_par_value");

                    b.Property<string>("Sigle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sigle");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("DefaultBranchId")
                        .HasDatabaseName("ix_tenants_default_branch_id");

                    b.HasIndex("Sigle")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_sigle");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.GlAccount", b =>
                {
                    b.HasOne("CPCREDO.Domain.Accounting.GlAccount", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gl_accounts_gl_accounts_parent_id");

                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gl_accounts_tenants_tenant_id");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.JournalEntry", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Identity.User", "PostedByUser")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_users_posted_by_user_id");

                    b.HasOne("CPCREDO.Domain.Accounting.JournalEntry", "ReversalOf")
                        .WithMany()
                        .HasForeignKey("ReversalOfJournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reversal_of_journal_id");

                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_tenants_tenant_id");

                    b.Navigation("Branch");

                    b.Navigation("PostedByUser");

                    b.Navigation("ReversalOf");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.JournalLine", b =>
                {
                    b.HasOne("CPCREDO.Domain.Accounting.GlAccount", "GlAccount")
                        .WithMany()
                        .HasForeignKey("GlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_gl_accounts_gl_account_id");

                    b.HasOne("CPCREDO.Domain.Accounting.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.Navigation("GlAccount");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.User", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("CPCREDO.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("CPCREDO.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.Member", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_members_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_members_tenants_tenant_id");

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.MemberTicket", b =>
                {
                    b.HasOne("CPCREDO.Domain.Identity.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_member_tickets_users_assigned_to_user_id");

                    b.HasOne("CPCREDO.Domain.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_tickets_users_created_by_user_id");

                    b.HasOne("CPCREDO.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_tickets_members_member_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.ShareAccount", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_share_accounts_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Members.Member", "Member")
                        .WithOne("ShareAccount")
                        .HasForeignKey("CPCREDO.Domain.Members.ShareAccount", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_share_accounts_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsAccount", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_accounts_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_accounts_members_member_id");

                    b.HasOne("CPCREDO.Domain.Savings.SavingsProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_accounts_savings_products_product_id");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsLedgerEntry", b =>
                {
                    b.HasOne("CPCREDO.Domain.Savings.SavingsAccount", "SavingsAccount")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_savings_ledger_entries_savings_accounts_savings_account_id");

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsLien", b =>
                {
                    b.HasOne("CPCREDO.Domain.Savings.SavingsAccount", "SavingsAccount")
                        .WithMany("Liens")
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_savings_liens_savings_accounts_savings_account_id");

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsProduct", b =>
                {
                    b.HasOne("CPCREDO.Domain.Accounting.GlAccount", null)
                        .WithMany()
                        .HasForeignKey("CashGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_products_gl_accounts_cash_gl_account_id");

                    b.HasOne("CPCREDO.Domain.Accounting.GlAccount", null)
                        .WithMany()
                        .HasForeignKey("LiabilityGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_products_gl_accounts_liability_gl_account_id");

                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_savings_products_tenants_tenant_id");
                });

            modelBuilder.Entity("CPCREDO.Domain.Teller.TillCountLine", b =>
                {
                    b.HasOne("CPCREDO.Domain.Teller.TillSession", "TillSession")
                        .WithMany("CountLines")
                        .HasForeignKey("TillSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_till_count_lines_till_sessions_till_session_id");

                    b.Navigation("TillSession");
                });

            modelBuilder.Entity("CPCREDO.Domain.Teller.TillSession", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_till_sessions_branches_branch_id");

                    b.HasOne("CPCREDO.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_till_sessions_users_user_id");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPCREDO.Domain.Tenancy.Branch", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CPCREDO.Domain.Tenancy.Tenant", b =>
                {
                    b.HasOne("CPCREDO.Domain.Tenancy.Branch", "DefaultBranch")
                        .WithMany()
                        .HasForeignKey("DefaultBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenants_branches_default_branch_id");

                    b.Navigation("DefaultBranch");
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.GlAccount", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CPCREDO.Domain.Accounting.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CPCREDO.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CPCREDO.Domain.Members.Member", b =>
                {
                    b.Navigation("ShareAccount");
                });

            modelBuilder.Entity("CPCREDO.Domain.Savings.SavingsAccount", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Liens");
                });

            modelBuilder.Entity("CPCREDO.Domain.Teller.TillSession", b =>
                {
                    b.Navigation("CountLines");
                });

            modelBuilder.Entity("CPCREDO.Domain.Tenancy.Tenant", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
